filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/tests/*'
        - 'app/Larapress/Tests/*'
        - 'app/assets/*'
        - 'app/filters.php'
        - 'app/start/*'
        - 'bootstrap/*'
        - 'docs/*'
        - _ide_helper.php
    paths: {  }
tools:
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/tests/*'
                - 'app/Larapress/Tests/*'
                - 'app/assets/*'
                - 'app/filters.php'
                - 'app/start/*'
                - 'bootstrap/*'
                - 'docs/*'
                - _ide_helper.php
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/tests/*'
                - 'app/Larapress/Tests/*'
                - 'app/assets/*'
                - 'app/filters.php'
                - 'app/start/*'
                - 'bootstrap/*'
                - 'docs/*'
                - _ide_helper.php
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/tests/*'
                - 'app/Larapress/Tests/*'
                - 'app/assets/*'
                - 'app/filters.php'
                - 'app/start/*'
                - 'bootstrap/*'
                - 'docs/*'
                - _ide_helper.php
            paths: {  }
        path_configs: {  }
    external_code_coverage:
        timeout: 1000
        enabled: true
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/tests/*'
                - 'app/Larapress/Tests/*'
                - 'app/assets/*'
                - 'app/filters.php'
                - 'app/start/*'
                - 'bootstrap/*'
                - 'docs/*'
                - _ide_helper.php
            paths: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/tests/*'
                - 'app/Larapress/Tests/*'
                - 'app/assets/*'
                - 'app/filters.php'
                - 'app/start/*'
                - 'bootstrap/*'
                - 'docs/*'
                - _ide_helper.php
            paths: {  }
before_commands: {  }
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }
